[package]
name = "orjson_ddb"
version = "0.2.2"
authors = ["Mattia Fantoni <mattia.fantoni@gmail.com>"]
description = "Fast Python ser/des for DynamoDB native JSON format"
edition = "2021"
resolver = "2"
rust-version = "1.57"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/MattFanto/orjson-ddb"
homepage = "https://github.com/MattFanto/orjson-ddb"
readme = "README.md"
keywords = ["fast", "json", "dynamodb", "aws", "boto3"]
include = [
    "Cargo.toml",
    "CHANGELOG.md",
    "data/*",
    "include",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "pyproject.toml",
    "README.md",
    "src/*",
    "test/*.py",
    "test/requirements.txt",
]

[lib]
name = "orjson_ddb"
crate-type = ["cdylib"]

[package.metadata.maturin]
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python",
    "Programming Language :: Rust",
    "Typing :: Typed",
]
python-source = "python"

[features]
default = []

# Use SIMD intrinsics. This requires Rust on the nightly channel.
unstable-simd = [
    "bytecount/generic-simd",
    "encoding_rs/simd-accel",
]

no-panic = [
    "itoa/no-panic",
    "ryu/no-panic",
]

# Build yyjson as a backend and panic if it fails. The default is to attempt
# to build and on failure fall back to another backend.
yyjson = []

[dependencies]
ahash = { version = "^0.8.6", default_features = false }
arrayvec = { version = "0.7", default_features = false, features = ["std", "serde"] }
associative-cache = { version = "2", default_features = false }
beef = { version = "0.5", default_features = false, features = ["impl_serde"] }
bytecount = { version = "^0.6.7", default_features = false, features = ["runtime-dispatch-simd"] }
chrono = { version = "^0.4.31", default_features = false }
compact_str = { version = "0.7", default_features = false, features = ["serde"] }
encoding_rs = { version = "0.8", default_features = false }
itoa = { version = "1", default_features = false }
itoap = { version = "1", features = ["std", "simd"] }
once_cell = { version = "1", default_features = false, features = ["race"] }
pyo3-ffi = { version = "^0.20", default_features = false, features = ["extension-module"]}
ryu = { version = "1", default_features = false }
serde = { version = "1", default_features = false }
serde_json = { version = "1", default_features = false, features = ["std", "float_roundtrip"] }
simdutf8 = { version = "0.1", default_features = false, features = ["std", "aarch64_neon"] }
smallvec = { version = "^1.11", default_features = false, features = ["union", "write"] }

[build-dependencies]
cc = { version = "1" }
pyo3-build-config = { version = "^0.20" }
version_check = { version = "0.9" }

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
lto = "off"
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = "thin"
opt-level = 3
panic = "abort"

[profile.release.build-override]
opt-level = 0
